defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

robot_cam_serial_numbers:
  - '244422300058' # close to the robot

cam_configs:
  width: 1280
  height: 720
  fps: 30
  processing_preset: 1 # High accuracy mode
  rotation_angle: 0

oculus_cam: -1 # Disable oculus cam
num_cams: 1

hydra:  
  output_subdir: null  
  run:  
    dir: .